name: app
type: "java:11"
disk: 1024
hooks:
    build:  mvn clean package payara-micro:bundle
web:
    commands:
        start: java -jar -Xmx$(jq .info.limits.memory /run/config.json)m -XX:+ExitOnOutOfMemoryError target/microprofile-microbundle.jar --port $PORT
